// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  Options as ClientOptions,
  TDataShape,
} from "@hey-api/client-axios";
import type {
  DeleteUsersData,
  GetData,
  GetUsersData,
  GetUsersResponse,
  PatchUsersData,
  PostUsersData,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * OpenAPI description (this document)
 */
export const get = <ThrowOnError extends boolean = false>(
  options?: Options<GetData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<unknown, unknown, ThrowOnError>(
    {
      url: "/",
      ...options,
    },
  );
};

export const deleteUsers = <ThrowOnError extends boolean = false>(
  options?: Options<DeleteUsersData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).delete<
    unknown,
    unknown,
    ThrowOnError
  >({
    url: "/users",
    ...options,
  });
};

export const getUsers = <ThrowOnError extends boolean = false>(
  options?: Options<GetUsersData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetUsersResponse,
    unknown,
    ThrowOnError
  >({
    url: "/users",
    ...options,
  });
};

export const patchUsers = <ThrowOnError extends boolean = false>(
  options?: Options<PatchUsersData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).patch<
    unknown,
    unknown,
    ThrowOnError
  >({
    url: "/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

export const postUsers = <ThrowOnError extends boolean = false>(
  options?: Options<PostUsersData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    unknown,
    unknown,
    ThrowOnError
  >({
    url: "/users",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};
