// This file is auto-generated by @hey-api/openapi-ts

export type Users = {
  /**
   * Note:
   * This is a Primary Key.<pk/>
   */
  id: number;
  username: string;
  email: string;
  created_at?: string;
};

export type GetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type GetResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteUsersData = {
  body?: never;
  headers?: {
    /**
     * Preference
     */
    Prefer?: "return=representation" | "return=minimal" | "return=none";
  };
  path?: never;
  query?: {
    id?: string;
    username?: string;
    email?: string;
    created_at?: string;
  };
  url: "/users";
};

export type DeleteUsersResponses = {
  /**
   * No Content
   */
  204: unknown;
};

export type GetUsersData = {
  body?: never;
  headers?: {
    /**
     * Limiting and Pagination
     */
    Range?: string;
    /**
     * Limiting and Pagination
     */
    "Range-Unit"?: string;
    /**
     * Preference
     */
    Prefer?: "count=none";
  };
  path?: never;
  query?: {
    id?: string;
    username?: string;
    email?: string;
    created_at?: string;
    /**
     * Filtering Columns
     */
    select?: string;
    /**
     * Ordering
     */
    order?: string;
    /**
     * Limiting and Pagination
     */
    offset?: string;
    /**
     * Limiting and Pagination
     */
    limit?: string;
  };
  url: "/users";
};

export type GetUsersResponses = {
  /**
   * OK
   */
  200: Array<Users>;
  /**
   * Partial Content
   */
  206: unknown;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type PatchUsersData = {
  /**
   * users
   */
  body?: Users;
  headers?: {
    /**
     * Preference
     */
    Prefer?: "return=representation" | "return=minimal" | "return=none";
  };
  path?: never;
  query?: {
    id?: string;
    username?: string;
    email?: string;
    created_at?: string;
  };
  url: "/users";
};

export type PatchUsersResponses = {
  /**
   * No Content
   */
  204: unknown;
};

export type PostUsersData = {
  /**
   * users
   */
  body?: Users;
  headers?: {
    /**
     * Preference
     */
    Prefer?:
      | "return=representation"
      | "return=minimal"
      | "return=none"
      | "resolution=ignore-duplicates"
      | "resolution=merge-duplicates";
  };
  path?: never;
  query?: {
    /**
     * Filtering Columns
     */
    select?: string;
  };
  url: "/users";
};

export type PostUsersResponses = {
  /**
   * Created
   */
  201: unknown;
};

export type ClientOptions = {
  baseURL: "http://0.0.0.0:3000/" | (string & {});
};
